name: publish to nuget
on:
  push:
    branches: [ main ]
    # tags:
    # - 'v*'
    # paths:
    # - 'nuget/ChillViking.TestUtils/**'

jobs:
  publish:
    name: test, build, pack & publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nuget/ChillViking.TestUtils
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Test ChillViking.TestUtils.NUnit'
      run: dotnet test ./ChillViking.TestUtils.NUnit.Tests/ChillViking.TestUtils.NUnit.Tests.csproj

    # - name: publish on version change
    #   id: publish_nuget
    #   uses: brandedoutcast/publish-nuget@v2
    #   with:
    #     PROJECT_FILE_PATH: ChillViking.TestUtils.NUnit/ChillViking.TestUtils.NUnit.csproj
    #     NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    #     BUILD_CONFIGURATION: Release
    #     VERSION_STATIC: 1.0.0
    #     INCLUDE_SYMBOLS: false
